[build]
  # Commande pour construire le frontend
  command = "cd client && npm install && npm run build"
  # Dossier o√π se trouve le site final
  publish = "client/dist"

[[redirects]]
  # Important pour que React fonctionne sans erreurs 404
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"